import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node", // environment (libraries, API, and etc.) to run the tests in
    coverage: {
      // testing coverage configuration
      provider: "v8", // v8 refers to the v8 engine used by Node.js and when set the coverage is generated by the v8 engine
      enabled: true,
      exclude: ["**/__generated__/**"], // files to exclude from coverage
    },
    include: ["src/**/*.test.ts"], // files to run when you run the tests
    root: ".",
  },
});
