/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List datasets
         * @description List datasets the user has access to.
         *
         *     The datasets are sorted by creation date, with the most recently created
         *     datasets coming first.
         *
         *     The dataset versions are not included in this response. To get the
         *     versions of a specific dataset, use the Get Dataset by ID endpoint.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["datasets_list"];
        put?: never;
        /**
         * Create a dataset
         * @description Create a new dataset with JSON examples. Empty datasets are not allowed.
         *
         *     **Payload Requirements**
         *     - The dataset name must be unique within the given space.
         *     - Each item in `examples[]` may contain **any user-defined fields**.
         *     - Do not include system-managed fields on input: `id`, `created_at`, `updated_at`.
         *     Requests that contain these fields in any example **will be rejected**.
         *     - Each example **must contain at least one property** (i.e., `{}` is invalid).
         *
         *     **Valid example** (create)
         *     ```json
         *     {
         *       "name": "my-dataset",
         *       "space_id": "spc_123",
         *       "examples": [
         *         {
         *           "question": "What is 2+2?",
         *           "answer": "4",
         *           "topic": "math"
         *         },
         *         {
         *           "question": "What is the capital of Spain?",
         *           "answer": "Madrid",
         *           "topic": "geography"
         *         },
         *       ]
         *     }
         *     ```
         *
         *     **Invalid example** ('id' not allowed on create)
         *     ```json
         *     {
         *       "name": "my-dataset",
         *       "space_id": "spc_123",
         *       "examples": [
         *         {
         *           "id": "ex_1",
         *           "input": "Hello"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        post: operations["datasets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a dataset
         * @description Get a dataset object by its ID.
         *
         *     This includes the dataset's versions, sorted by creation date, with
         *     the most recently-created version first.
         *
         *     This endpoint does not include the dataset's examples. To get the examples
         *     of a specific dataset version, use the List Dataset Examples endpoint.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["datasets_get"];
        put?: never;
        post?: never;
        /**
         * Delete a dataset
         * @description Delete a dataset by its ID. This operation is irreversible.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        delete: operations["datasets_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/datasets/{dataset_id}/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dataset examples
         * @description List examples for a given dataset and version.
         *
         *     If version is not passed, the latest version is selected. Examples are
         *     sorted by insertion order.
         *
         *     **Pagination**:
         *     - Response includes `pagination` for forward compatibility.
         *     - **Currently not implemented**: `pagination.next_cursor` is omitted
         *     - When pagination is enabled in the future, the behavior will match
         *     other list endpoints (cursor-based, opaque tokens).
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["datasets_examples_list"];
        put?: never;
        /**
         * Add new examples to a dataset
         * @description Appends new examples to an existing dataset.
         *
         *     If the dataset version is not passed, the latest version is selected.
         *     The inserted examples will be assigned autogenerated, unique IDs.
         *
         *     **Payload Requirements**
         *     - Each item in `examples[]` may contain any user-defined fields.
         *     - Do not include system-managed fields on input: `id`, `created_at`,
         *     `updated_at`. Requests that contain these fields in any example will
         *     be rejected.
         *     - Each example must contain at least one property (i.e., `{}` is invalid).
         *
         *     **Valid example** (create)
         *     ```json
         *     {
         *       "examples": [
         *         { "question": "What is 2+2?",
         *           "answer": "4",
         *           "topic": "math"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     **Invalid example** ('id' not allowed on create)
         *     ```json
         *     {
         *       "examples": [
         *         {
         *           "id": "ex_1",
         *           "input": "Hello"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        post: operations["datasets_examples_insert"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update existing examples in a dataset
         * @description Updates existing dataset examples by matching their `id` field.
         *
         *     an example ID does not match any existing example in the dataset
         *     version, it will be ignored. In other words, only examples with IDs
         *     that already exist will be updated. To add new examples, use the
         *     Insert Dataset Examples endpoint.
         *
         *     Adding columns that do not exist in the dataset schema is allowed, but
         *     removing existing columns is not.
         *
         *     Optionally, the update can create a new version of the dataset. In
         *     this case, the outcome of the update will be reflected only in the new
         *     version, while the previous version remains unchanged. If a new
         *     version is not created, the updates will be applied directly (in place)
         *     to the specified version.
         *
         *     **Payload Requirements**
         *     - Each item in `examples[]` may contain any user-defined fields.
         *     - Each item in `examples[]` must include the `id` field to identify the
         *     example to update.
         *     - Do not include system-managed fields on input: `created_at`, `updated_at`.
         *     Requests that contain these fields in any example will be rejected.
         *     - Each example must contain at least one property (i.e., `{}` is invalid).
         *
         *     **Valid example** (create)
         *     ```json
         *     {
         *       "examples": [
         *         {
         *           "id": "ex_001",
         *           "question": "What is 2+2?",
         *           "answer": "4",
         *           "topic": "math"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     **Invalid example** ('id' missing for update)
         *     ```json
         *     {
         *       "examples": [
         *         {
         *           "input": "Hello"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        patch: operations["datasets_examples_update"];
        trace?: never;
    };
    "/v2/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List experiments
         * @description List all experiments a user has access to.
         *
         *     To filter experiments by the dataset they were run on, provide the
         *     `dataset_id` query parameter.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["experiments_list"];
        put?: never;
        /**
         * Create an experiment
         * @description Create a new experiment. Empty experiments are not allowed.
         *
         *     Experiments are composed of "runs". Each experiment run (JSON object)
         *     must include an `example_id` field that corresponds to an example in
         *     the dataset, and a `output` field that contains the task's output for
         *     the example (the input).
         *
         *     Payload Requirements
         *     - The `name` must be unique within the target dataset
         *     - Provide at least one run in `experiment_runs`.
         *     - Each run must include:
         *       - `example_id` -- the ID of an existing example in the dataset/version
         *       - `output` -- model/task output for that example
         *       - You may include any additional fields per run that can be used for
         *       analysis or filtering. For exampple: `model`, `latency_ms`,
         *       `temperature`, `prompt`, `tool_calls`, etc.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        post: operations["experiments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an experiment
         * @description Get an experiment object by its ID.
         *
         *     The response does not include the experiment's runs. To get the runs of
         *     a specific experiment, use the List Experiment Runs endpoint.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["experiments_get"];
        put?: never;
        post?: never;
        /**
         * Delete an experiment
         * @description Delete an experiment by its ID. This operation is irreversible.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        delete: operations["experiments_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/experiments/{experiment_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List experiment runs
         * @description List runs for a given experiment.
         *
         *     The runs are sorted by insertion order.
         *
         *     **Pagination**:
         *     - Response includes `pagination` for forward compatibility.
         *     - **Currently not implemented**: `pagination.next_cursor` is omitted
         *     - When pagination is enabled in the future, the behavior will match
         *     other list endpoints (cursor-based, opaque tokens).
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["experiments_runs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List prompts
         * @description List prompts the user has access to.
         *
         *     The prompts are sorted by update date, with the most recently updated
         *     prompts coming first.
         *
         *     <Warning>This endpoint is in alpha, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Warning>
         */
        get: operations["prompts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a prompt
         * @description Get a specific prompt by its ID.
         *
         *     <Warning>This endpoint is in alpha, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Warning>
         */
        get: operations["prompts_get"];
        put?: never;
        post?: never;
        /**
         * Delete a prompt
         * @description Delete a prompt by its ID. This operation is irreversible.
         *
         *     <Warning>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Warning>
         */
        delete: operations["prompts_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description List projects the user has access to.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["projects_list"];
        put?: never;
        /**
         * Create a project
         * @description Create a new project given a name and space ID.
         *
         *     **Payload Requirements**
         *     - The project name must be unique within the given space.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        post: operations["projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a project
         * @description Get a specific project by its ID.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        get: operations["projects_get"];
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Delete a project by its ID. This operation is irreversible.
         *
         *     <Note>This endpoint is in beta, read more [here](https://arize.com/docs/ax/rest-reference#api-version-stages).</Note>
         */
        delete: operations["projects_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A project represents an LLM application and serves as the primary container for observability data. Each project collects traces and spans that capture the execution flow of your application, enabling you to debug issues, monitor latency, and analyze token usage.
         *     Projects belong to a space and provide a centralized view of your application's performance. Use projects to organize related traces, run experiments against datasets, and track improvements over time.
         */
        Project: {
            /** @description The project ID */
            id: string;
            /** @description The project name */
            name: string;
            /** @description The space ID the project belongs to */
            space_id: string;
            /**
             * Format: date-time
             * @description When the project was created
             */
            created_at: string;
        };
        /**
         * @description A prompt is a reusable template for LLM interactions. Prompts can be versioned
         *     and labeled to track changes over time. Use prompts to standardize how you
         *     interact with LLMs across your application.
         */
        Prompt: {
            /** @description The prompt ID */
            id: string;
            /** @description The prompt name */
            name: string;
            /** @description The prompt description */
            description?: string | null;
            /** @description The space ID the prompt belongs to */
            space_id: string;
            /**
             * Format: date-time
             * @description When the prompt was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the prompt was last updated
             */
            updated_at: string;
            /** @description The user ID of the user who created the prompt */
            created_by_user_id: string;
            /** @description The tags associated with the prompt */
            tags?: string[];
        };
        /**
         * @description A dataset is a structured collection of examples used to test and evaluate
         *     LLM applications. Datasets allow you to test models consistently across
         *     any real-world scenarios and edge cases, quickly identify regressions,
         *     and track measurable improvements.
         */
        Dataset: {
            /** @description Unique identifier for the dataset */
            id: string;
            /** @description Name of the dataset */
            name: string;
            /** @description Unique identifier for the space this dataset belongs to */
            space_id: string;
            /**
             * Format: date-time
             * @description Timestamp for when the dataset was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Timestamp for the last update of the dataset
             */
            updated_at: string;
            /** @description List of versions associated with this dataset */
            versions?: components["schemas"]["DatasetVersion"][];
        };
        /**
         * @description A dataset version is a saved snapshot of a dataset. Arize stores datasets
         *     as version-controlled collections of examples for experiments.
         *     When you update a dataset, you can do so inplace  or create a new version
         *     while preserving access to previous versions.
         */
        DatasetVersion: {
            /** @description Unique identifier for the dataset version */
            id: string;
            /** @description Name of the dataset version */
            name: string;
            /** @description Unique identifier for the dataset this version belongs to */
            dataset_id: string;
            /**
             * Format: date-time
             * @description Timestamp for when the dataset version was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Timestamp for the last update of the dataset version
             */
            updated_at: string;
        };
        /**
         * @description Experiments combine a dataset (example inputs/expected outputs), a task
         *     (the function that produces model outputs), and one or more evaluators
         *     (code or LLM judges) to measure performance. Each run is stored independently
         *     so you can compare runs, track progress, and validate improvements over time.
         *     See the full definition on the Experiments page.
         *
         *     Use an experiment to run tasks on a dataset, attach evaluators to score outputs,
         *     and compare runs to confirm improvements.
         */
        Experiment: {
            /** @description Unique identifier for the experiment */
            id: string;
            /** @description Name of the experiment */
            name: string;
            /** @description Unique identifier for the dataset this experiment belongs to */
            dataset_id: string;
            /** @description Unique identifier for the dataset version this experiment belongs to */
            dataset_version_id: string;
            /**
             * Format: date-time
             * @description Timestamp for when the experiment was created
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Timestamp for the last update of the experiment
             */
            updated_at: string;
            /** @description Unique identifier for the experiment traces project this experiment belongs to (if it exists) */
            experiment_traces_project_id?: string;
        };
        /**
         * @description Cursor-based pagination metadata. Use `next_cursor` in the subsequent
         *     request's `cursor` query parameter.
         */
        PaginationMetadata: {
            /**
             * @description Opaque cursor for fetching the next page. Treat as an unreadable token.
             *     Present when `has_more` is true; omitted when `hasMore` is false.
             */
            next_cursor?: string;
            /** @description True if another page of results is available. */
            has_more: boolean;
        };
        /**
         * @description A dataset example with arbitrary user-defined fields. System-managed
         *     fields are excluded for creation requests.
         */
        DatasetExampleCreate: {
            [key: string]: unknown;
        };
        /**
         * @description A dataset example with arbitrary user-defined fields. System-managed
         *     fields, except 'id', are excluded for update requests.
         */
        DatasetExampleUpdate: {
            /** @description System-assigned unique ID for the example */
            id: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description A dataset example with arbitrary user-defined fields. System-managed
         *     fields are included as read-only for responses.
         */
        DatasetExample: {
            /** @description System-assigned unique ID for the example */
            readonly id: string;
            /**
             * Format: date-time
             * @description Timestamp for when the example was created
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description Timestamp for the last update of the example
             */
            readonly updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** @description An experiment run with experiment data including outputs, evaluations, and trace metadata */
        ExperimentRunCreate: {
            /** @description ID of the dataset example associated with this experiment run */
            example_id: string;
            /** @description output of the task for the matching example */
            output: string;
        } & {
            [key: string]: unknown;
        };
        /** @description An experiment run with experiment data including outputs, evaluations, and trace metadata */
        ExperimentRun: {
            /** @description System-assigned unique ID for the example */
            readonly id: string;
            /** @description ID of the dataset example associated with this experiment run */
            readonly example_id: string;
            /** @description output of the task for the matching example */
            output: string;
        } & {
            [key: string]: unknown;
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            /** @description A short, human-readable summary of the problem type */
            title: string;
            /** @description The HTTP status code generated by the origin server for this occurrence of the problem */
            status: number;
            /**
             * Format: uri-reference
             * @description A URI reference that identifies the problem type
             */
            type?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem */
            detail?: string;
            /**
             * Format: uri-reference
             * @description A URI reference that identifies the specific occurrence of the problem
             */
            instance?: string;
        };
        /** @description A universally unique identifier */
        Id: string;
    };
    responses: {
        /** @description A dataset object */
        Dataset: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "dataset_001",
                 *       "created_at": "2024-01-01T12:00:00Z",
                 *       "updated_at": "2024-01-02T12:00:00Z",
                 *       "name": "Sample Dataset",
                 *       "space_id": "spc_123",
                 *       "versions": [
                 *         {
                 *           "id": "dv_001",
                 *           "name": "v1.0",
                 *           "dataset_id": "dataset_001",
                 *           "created_at": "2024-01-01T12:00:00Z",
                 *           "updated_at": "2024-01-02T12:00:00Z"
                 *         },
                 *         {
                 *           "id": "dv_002",
                 *           "name": "v1.1",
                 *           "dataset_id": "dataset_001",
                 *           "created_at": "2024-02-01T12:00:00Z",
                 *           "updated_at": "2024-02-02T12:00:00Z"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Dataset"];
            };
        };
        /** @description Returns a list of dataset objects */
        DatasetList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "datasets": [
                 *         {
                 *           "id": "dataset_001",
                 *           "created_at": "2024-01-01T12:00:00Z",
                 *           "updated_at": "2024-01-02T12:00:00Z",
                 *           "name": "Sample Dataset 1",
                 *           "space_id": "spc_123"
                 *         },
                 *         {
                 *           "id": "dataset_002",
                 *           "created_at": "2024-01-02T12:00:00Z",
                 *           "updated_at": "2024-01-03T12:00:00Z",
                 *           "name": "Sample Dataset 2",
                 *           "space_id": "spc_123"
                 *         },
                 *         {
                 *           "id": "dataset_003",
                 *           "created_at": "2024-01-03T12:00:00Z",
                 *           "updated_at": "2024-01-04T12:00:00Z",
                 *           "name": "Sample Dataset 3",
                 *           "space_id": "spc_456"
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description A list of datasets */
                    datasets: components["schemas"]["Dataset"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description Dataset successfully deleted */
        DatasetDeleted: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Returns a list of dataset examples as structured objects */
        DatasetExampleList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "examples": [
                 *         {
                 *           "id": "ex_001",
                 *           "created_at": "2024-01-01T12:00:00Z",
                 *           "updated_at": "2024-01-02T12:00:00Z",
                 *           "question": "What is 2 + 2?",
                 *           "answer": 4,
                 *           "topic": "arithmetic",
                 *           "isCorrect": true
                 *         },
                 *         {
                 *           "id": "ex_002",
                 *           "created_at": "2024-01-02T12:00:00Z",
                 *           "updated_at": "2024-01-03T12:00:00Z",
                 *           "question": "What is the square root of 16?",
                 *           "answer": 4,
                 *           "topic": "geometry",
                 *           "isCorrect": true
                 *         },
                 *         {
                 *           "id": "ex_003",
                 *           "created_at": "2024-01-03T12:00:00Z",
                 *           "updated_at": "2024-01-04T12:00:00Z",
                 *           "question": "If 3x = 12, what is x?",
                 *           "answer": 3,
                 *           "topic": "algebra",
                 *           "isCorrect": false
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description Array of example objects from the dataset */
                    examples: components["schemas"]["DatasetExample"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description An experiment object */
        Experiment: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "exp_001",
                 *       "name": "Experiment 1",
                 *       "dataset_id": "dataset_001",
                 *       "dataset_version_id": "dv_001",
                 *       "created_at": "2024-01-01T12:00:00Z",
                 *       "updated_at": "2024-01-02T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Experiment"];
            };
        };
        /** @description Returns a list of experiment objects */
        ExperimentList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "experiments": [
                 *         {
                 *           "id": "exp_001",
                 *           "name": "Experiment 1",
                 *           "dataset_id": "dataset_001",
                 *           "dataset_version_id": "dv_001",
                 *           "created_at": "2024-01-01T12:00:00Z",
                 *           "updated_at": "2024-01-02T12:00:00Z"
                 *         },
                 *         {
                 *           "id": "exp_002",
                 *           "name": "Experiment 2",
                 *           "dataset_id": "dataset_002",
                 *           "dataset_version_id": "dv_002",
                 *           "created_at": "2024-01-02T12:00:00Z",
                 *           "updated_at": "2024-01-03T12:00:00Z"
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description A list of experiments */
                    experiments: components["schemas"]["Experiment"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description Experiment successfully deleted */
        ExperimentDeleted: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Returns a list of experiment run objects */
        ExperimentRunsList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "experiment_runs": [
                 *         {
                 *           "id": "run_001",
                 *           "example_id": "ex_001",
                 *           "output": "4",
                 *           "latency_ms": 120,
                 *           "model": "gpt-4"
                 *         },
                 *         {
                 *           "id": "run_002",
                 *           "example_id": "ex_002",
                 *           "output": "4",
                 *           "latency_ms": 150,
                 *           "model": "gpt-4"
                 *         },
                 *         {
                 *           "id": "run_003",
                 *           "example_id": "ex_003",
                 *           "output": "3",
                 *           "latency_ms": 130,
                 *           "model": "gpt-4"
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description Array of experiment run objects containing experiment fields and evaluations */
                    experiment_runs: components["schemas"]["ExperimentRun"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description A project object */
        Project: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "project_001",
                 *       "name": "My Project",
                 *       "space_id": "space_12345",
                 *       "created_at": "2024-01-01T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Project"];
            };
        };
        /** @description Returns a list of project objects */
        ProjectList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "projects": [
                 *         {
                 *           "id": "project_001",
                 *           "name": "My Project",
                 *           "space_id": "space_12345",
                 *           "created_at": "2024-01-01T12:00:00Z"
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description A list of projects */
                    projects: components["schemas"]["Project"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description A prompt object */
        Prompt: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "prompt_001",
                 *       "name": "My Prompt",
                 *       "description": "A prompt for customer support",
                 *       "space_id": "space_12345",
                 *       "created_at": "2024-01-01T12:00:00Z",
                 *       "updated_at": "2024-01-02T12:00:00Z",
                 *       "created_by_user_id": "user_12345",
                 *       "tags": [
                 *         "customer-support",
                 *         "help-desk"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Prompt"];
            };
        };
        /** @description Returns a list of prompt objects */
        PromptList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "prompts": [
                 *         {
                 *           "id": "prompt_001",
                 *           "name": "My Prompt",
                 *           "description": "A prompt for customer support",
                 *           "space_id": "space_12345",
                 *           "created_at": "2024-01-01T12:00:00Z",
                 *           "updated_at": "2024-01-02T12:00:00Z",
                 *           "created_by_user_id": "user_12345",
                 *           "tags": [
                 *             "customer-support",
                 *             "help-desk"
                 *           ]
                 *         }
                 *       ],
                 *       "pagination": {
                 *         "next_cursor": "cursor_12345",
                 *         "has_more": true
                 *       }
                 *     }
                 */
                "application/json": {
                    /** @description A list of prompts */
                    prompts: components["schemas"]["Prompt"][];
                    /** @description Pagination metadata for cursor-based navigation */
                    pagination: components["schemas"]["PaginationMetadata"];
                };
            };
        };
        /** @description Project successfully deleted */
        ProjectDeleted: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Prompt successfully deleted */
        PromptDeleted: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 400,
                 *       "title": "Invalid request parameters",
                 *       "detail": "The 'name' field is required and must be a non-empty string.",
                 *       "instance": "/resource",
                 *       "type": "https://example.com/probs/invalid-request"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 401,
                 *       "title": "Authentication required",
                 *       "detail": "You must be authenticated to access this resource.",
                 *       "instance": "/resource",
                 *       "type": "https://example.com/probs/authentication-required"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Insufficient permissions to access this resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 403,
                 *       "title": "Access forbidden",
                 *       "detail": "You do not have permission to access this resource.",
                 *       "instance": "/resource/12345",
                 *       "type": "https://example.com/probs/access-forbidden"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 404,
                 *       "title": "Resource not found",
                 *       "detail": "The requested resource with ID '12345' was not found.",
                 *       "instance": "/resource/12345",
                 *       "type": "https://example.com/probs/resource-not-found"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 409,
                 *       "title": "Resource conflict",
                 *       "detail": "A resource with the given identifier already exists.",
                 *       "instance": "/resource",
                 *       "type": "https://example.com/probs/resource-conflict"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimitExceeded: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": 429,
                 *       "title": "Rate limit exceeded",
                 *       "detail": "You have exceeded the allowed number of requests. Please try again later.",
                 *       "instance": "/resource",
                 *       "type": "https://example.com/probs/rate-limit-exceeded"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The unique identifier of the dataset */
        DatasetIdPathParam: components["schemas"]["Id"];
        /** @description The unique identifier of the experiment */
        ExperimentIdPathParam: components["schemas"]["Id"];
        /**
         * @description The unique identifier of the project
         * @example project_12345
         */
        ProjectIdPathParam: components["schemas"]["Id"];
        /**
         * @description The unique identifier of the prompt
         * @example prompt_12345
         */
        PromptIdPathParam: components["schemas"]["Id"];
        /** @description Filter search results to a particular space ID */
        SpaceIdQueryParam: components["schemas"]["Id"];
        /** @description Filter experiments to a particular dataset ID */
        DatasetIdQueryParam: components["schemas"]["Id"];
        /** @description The unique identifier of the dataset version */
        DatasetVersionIdQueryParam: components["schemas"]["Id"];
        /** @description Maximum items to return */
        LimitQueryParamMax100: number;
        /** @description Maximum items to return */
        LimitQueryParamMax500: number;
        /**
         * @description Opaque pagination cursor returned from a previous response
         *     (`pagination.next_cursor`). Treat it as an unreadable token; do not
         *     attempt to parse or construct it.
         */
        CursorQueryParam: string;
    };
    requestBodies: {
        /** @description Body containing project creation parameters */
        CreateProjectRequestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "My Project",
                 *       "space_id": "space_12345"
                 *     }
                 */
                "application/json": {
                    /** @description Name of the project (must be unique within the space) */
                    name: string;
                    /** @description ID of the space to create the project in */
                    space_id: string;
                };
            };
        };
        /** @description Body containing dataset creation parameters */
        CreateDatasetRequestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Math Questions Dataset",
                 *       "space_id": "space_12345",
                 *       "examples": [
                 *         {
                 *           "question": "What is 2 + 2?",
                 *           "answer": "4",
                 *           "topic": "arithmetic"
                 *         },
                 *         {
                 *           "question": "What is the square root of 16?",
                 *           "answer": "4",
                 *           "topic": "geometry"
                 *         },
                 *         {
                 *           "question": "If 3x = 12, what is x?",
                 *           "answer": "4",
                 *           "topic": "algebra"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @description Name of the new dataset */
                    name: string;
                    /** @description ID of the space the dataset will belong to */
                    space_id: string;
                    /** @description Array of examples for the new dataset */
                    examples: components["schemas"]["DatasetExampleCreate"][];
                };
            };
        };
        /** @description Body containing dataset examples for insert (append) operation with auto-generated IDs */
        InsertDatasetExamplesRequestBody: {
            content: {
                /**
                 * @example {
                 *       "examples": [
                 *         {
                 *           "question": "What is 2 + 2?",
                 *           "answer": "4",
                 *           "topic": "arithmetic"
                 *         },
                 *         {
                 *           "question": "What is the square root of 16?",
                 *           "answer": "4",
                 *           "topic": "geometry"
                 *         },
                 *         {
                 *           "question": "If 3x = 12, what is x?",
                 *           "answer": "4",
                 *           "topic": "algebra"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @description Array of examples to append to the dataset version */
                    examples: components["schemas"]["DatasetExampleCreate"][];
                };
            };
        };
        /** @description Body containing dataset examples for update operation by ID matching */
        UpdateDatasetExamplesRequestBody: {
            content: {
                /**
                 * @example {
                 *       "examples": [
                 *         {
                 *           "id": "example_001",
                 *           "question": "What is 2 * 2?"
                 *         },
                 *         {
                 *           "id": "example_002",
                 *           "question": "What is the square root of 64?",
                 *           "answer": "8"
                 *         },
                 *         {
                 *           "id": "example_003",
                 *           "question": "If 9x = 36, what is x?",
                 *           "topic": "algebra"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @description Array of examples with 'id' field for matching and updating existing records */
                    examples: components["schemas"]["DatasetExampleUpdate"][];
                    /**
                     * @description Name for the new version. If provided (non-empty), creates a
                     *     new version with that name.
                     *
                     *     If omitted or empty, updates the existing version in-place.
                     */
                    new_version?: string;
                };
            };
        };
        /** @description Body containing experiment creation parameters */
        CreateExperimentRequestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "My Experiment Name",
                 *       "dataset_id": "dataset_12345",
                 *       "experiment_runs": [
                 *         {
                 *           "example_id": "example_001",
                 *           "output": "4",
                 *           "model": "gpt-4o-mini",
                 *           "temperature": 0.2,
                 *           "latency_ms": 118,
                 *           "prompt": "Answer the math question briefly."
                 *         },
                 *         {
                 *           "example_id": "example_002",
                 *           "output": "4",
                 *           "model": "gpt-4o-mini",
                 *           "temperature": 0.2,
                 *           "latency_ms": 132
                 *         },
                 *         {
                 *           "example_id": "example_003",
                 *           "output": "4",
                 *           "model": "gpt-4o-mini",
                 *           "temperature": 0.2,
                 *           "latency_ms": 125
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": {
                    /** @description Name of the experiment */
                    name: string;
                    /** @description ID of the dataset to create the experiment for */
                    dataset_id: string;
                    /** @description Array of experiment run data */
                    experiment_runs: components["schemas"]["ExperimentRunCreate"][];
                };
            };
        };
    };
    headers: {
        /**
         * @description When throttled (429), how long to wait before retrying. Value is
         *     either a delta-seconds integer.
         * @example 42
         */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    datasets_list: {
        parameters: {
            query?: {
                /** @description Filter search results to a particular space ID */
                space_id?: components["parameters"]["SpaceIdQueryParam"];
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax100"];
                /**
                 * @description Opaque pagination cursor returned from a previous response
                 *     (`pagination.next_cursor`). Treat it as an unreadable token; do not
                 *     attempt to parse or construct it.
                 */
                cursor?: components["parameters"]["CursorQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DatasetList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    datasets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateDatasetRequestBody"];
        responses: {
            201: components["responses"]["Dataset"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the dataset */
                dataset_id: components["parameters"]["DatasetIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Dataset"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    datasets_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the dataset */
                dataset_id: components["parameters"]["DatasetIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["DatasetDeleted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    datasets_examples_list: {
        parameters: {
            query?: {
                /** @description The unique identifier of the dataset version */
                dataset_version_id?: components["parameters"]["DatasetVersionIdQueryParam"];
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax500"];
            };
            header?: never;
            path: {
                /** @description The unique identifier of the dataset */
                dataset_id: components["parameters"]["DatasetIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DatasetExampleList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    datasets_examples_insert: {
        parameters: {
            query?: {
                /** @description The unique identifier of the dataset version */
                dataset_version_id?: components["parameters"]["DatasetVersionIdQueryParam"];
            };
            header?: never;
            path: {
                /** @description The unique identifier of the dataset */
                dataset_id: components["parameters"]["DatasetIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["InsertDatasetExamplesRequestBody"];
        responses: {
            200: components["responses"]["Dataset"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    datasets_examples_update: {
        parameters: {
            query?: {
                /** @description The unique identifier of the dataset version */
                dataset_version_id?: components["parameters"]["DatasetVersionIdQueryParam"];
            };
            header?: never;
            path: {
                /** @description The unique identifier of the dataset */
                dataset_id: components["parameters"]["DatasetIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateDatasetExamplesRequestBody"];
        responses: {
            200: components["responses"]["Dataset"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    experiments_list: {
        parameters: {
            query?: {
                /** @description Filter experiments to a particular dataset ID */
                dataset_id?: components["parameters"]["DatasetIdQueryParam"];
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax100"];
                /**
                 * @description Opaque pagination cursor returned from a previous response
                 *     (`pagination.next_cursor`). Treat it as an unreadable token; do not
                 *     attempt to parse or construct it.
                 */
                cursor?: components["parameters"]["CursorQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ExperimentList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    experiments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateExperimentRequestBody"];
        responses: {
            201: components["responses"]["Experiment"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the experiment */
                experiment_id: components["parameters"]["ExperimentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Experiment"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    experiments_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the experiment */
                experiment_id: components["parameters"]["ExperimentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["ExperimentDeleted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    experiments_runs_list: {
        parameters: {
            query?: {
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax500"];
            };
            header?: never;
            path: {
                /** @description The unique identifier of the experiment */
                experiment_id: components["parameters"]["ExperimentIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ExperimentRunsList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    prompts_list: {
        parameters: {
            query?: {
                /** @description Filter search results to a particular space ID */
                space_id?: components["parameters"]["SpaceIdQueryParam"];
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax100"];
                /**
                 * @description Opaque pagination cursor returned from a previous response
                 *     (`pagination.next_cursor`). Treat it as an unreadable token; do not
                 *     attempt to parse or construct it.
                 */
                cursor?: components["parameters"]["CursorQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PromptList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the prompt
                 * @example prompt_12345
                 */
                prompt_id: components["parameters"]["PromptIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Prompt"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    prompts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the prompt
                 * @example prompt_12345
                 */
                prompt_id: components["parameters"]["PromptIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["PromptDeleted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    projects_list: {
        parameters: {
            query?: {
                /** @description Filter search results to a particular space ID */
                space_id?: components["parameters"]["SpaceIdQueryParam"];
                /** @description Maximum items to return */
                limit?: components["parameters"]["LimitQueryParamMax100"];
                /**
                 * @description Opaque pagination cursor returned from a previous response
                 *     (`pagination.next_cursor`). Treat it as an unreadable token; do not
                 *     attempt to parse or construct it.
                 */
                cursor?: components["parameters"]["CursorQueryParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ProjectList"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateProjectRequestBody"];
        responses: {
            201: components["responses"]["Project"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the project
                 * @example project_12345
                 */
                project_id: components["parameters"]["ProjectIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Project"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    projects_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The unique identifier of the project
                 * @example project_12345
                 */
                project_id: components["parameters"]["ProjectIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["ProjectDeleted"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
}
